# Generated by Django 2.2.4 on 2020-01-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_flat_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner_phone_pure',
            field=models.CharField(blank=True, max_length=20, verbose_name='Нормализованый номер владельца:'),
        ),
    ]
