# Generated by Django 2.2.4 on 2020-01-25 17:16

from django.db import migrations

def customer(apps,scheme_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            customer=flat.owner,
            customer_phonenumber=flat.owners_phonenumber,
            customer_phone_pure=flat.owner_phone_pure
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.RunPython(customer)
    ]
