# Generated by Django 2.2.4 on 2020-01-25 17:19

from django.db import migrations

def customer_flat(apps,schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner = Owner.objects.filter(customer=flat.owner)
        owner[0].customer_flat.set([flat])
        owner[0].save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20200125_2016'),
    ]

    operations = [
        migrations.RunPython(customer_flat)
    ]
