# Generated by Django 2.2.4 on 2020-01-25 17:40

from django.db import migrations


def delete(apps,schema_editor):
    Flat = apps.get_model('property', 'FLat')


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20200125_2019'),
    ]

    operations = [
        migrations.RunPython(delete)
    ]
