# Generated by Django 2.2.4 on 2020-01-29 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20200125_2040'),
    ]

    operations = [
    ]
